channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python >=3.12
  - conda-forge::mamba >=1.5.8
  - conda-forge::pip >= 24.1.2
  - conda-forge::graphviz >= 0.20.3
  - pip:
     - "."