[tool.poetry]
name = "omni"
version = "0.1.0"
description = ""
authors = ["almutlue <almut.lue@gmail.com>", "Izaskun Mallona <izaskun.mallona@gmail.com>"]
readme = "README.md"
packages = [{include = "omni"}]
homepage = "https://github.com/omnibenchmark/omni-py"
repository = "https://github.com/omnibenchmark/omni-py"
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python"
]

[tool.poetry.dependencies]
python = "^3.12" # so snmk >8 is installable
omni-schema = {git = "https://github.com/omnibenchmark/omni-schema.git", rev = "version/0.0.2"}
typer = {extras = ["all"], version = "^0.12.3"}
typing-extensions = "^4.11.0"
easybuild="^4.9.1"
snakemake="^8.11.6"
snakedeploy="^0.10.0"
#snakemake-interface-common="^1.17.2"
#snakemake-interface-executor-plugins="^9.2.0"
setuptools="^70.0.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.0"
black = "^23.12.0"
pytest-cov = "^4.1.0"


[tool.poetry.group.test.dependencies]
genbadge = {extras = ["coverage", "tests"], version = "^1.1.1"}

[tool.poetry.scripts]
ob = 'omni.cli.main:cli'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# dynamic = ["dependencies"]

# [tool.setuptools.dynamic]
# dependencies = { file = ["requirements.txt"] }

# [tool.pytest.ini_options]
# testpaths = [
#     "tests/software",
# ]