[tool.poetry]
name = "omnibenchmark"
version = "0.0.0" # Placeholder, managed by poetry-dynamic-versioning
description = "An tool for automated scientific benchmarking"
authors = [
    "almutlue <almut.lue@gmail.com>",
    "Izaskun Mallona <izaskun.mallona@gmail.com>",
    "Daniel Incicau <daniel.incicau@gmail.com>",
]
readme = "README.md"
packages = [{ include = "omni" }]
homepage = "https://github.com/omnibenchmark/omni-py"
repository = "https://github.com/omnibenchmark/omni-py"
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
]

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"


[tool.poetry.dependencies]
python = "^3.12"
click = "^8.1.7"
aiohttp = "^3.9.5"
async = "^0.6.2"
tqdm = "^4.66.4"
requests = "^2.31.0"
python-dateutil = "^2.9.0.post0"

matplotlib = "3.8.0"
networkx = "^3.3"
pydot = "^3.0.2"

omni-schema = { git = "https://github.com/omnibenchmark/omni-schema.git", rev = "version/0.0.5" }

snakemake = "8.25.1"
snakedeploy = "^0.10.0"

easybuild = "^4.9.2"
easybuild-easyblocks = "^4.9.2"

minio = { version = "^7.2.7", optional = true }
boto3 = { version = "^1.34.102", optional = true }
snakemake-storage-plugin-s3 = { version = "^0.2.12", optional = true }

[tool.poetry.extras]
s3 = ["minio", "boto3", "snakemake-storage-plugin-s3"]

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.7.1"
black = "^23.12.0"
typing-extensions = "^4.11.0"
isort = "^5.13.2"
pyright = "^1.1.398"


[tool.poetry.group.test.dependencies]
pytest-cov = "^4.1.0"
pytest-split = "^0.9.0"
pytest-xdist = "^3.6.1"
genbadge = { extras = ["coverage", "tests"], version = "^1.1.1" }
argparse = "^1.4.0"
testcontainers = "^4.5.1"

s3fs = { extras = ["boto3"], version = ">=2023.12.0" }
boto3 = "*"
botocore = "*"
pytest-timeout = "^2.3.1"

[tool.poetry.scripts]
ob = 'omni.cli.main:cli'

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.isort]
profile = "black"
