channels:
  - conda-forge
  - bioconda
dependencies:
  - python == 3.12
  - conda-forge::python >=3.12
  - conda-forge::mamba >=1.5.8
  - pip
  - pip:
    - https://github.com/omnibenchmark/omni-py/archive/sw_imallona.zip

    